wsl = false
multigrid = false
vsync = true
maximized = false
srgb = false
idle = true
# neovim_bin = "/home/bucchiman/bin/nvim"
# neovim_bin = "/opt/local/bin/nvim"
# neovim_bin = "/home/yk.iwabuchi/bin/nvim"
frame = "Full"

