# FileName:     Makefile
# Author: 8ucchiman
# CreatedDate:  2023-02-03 21:27:49 +0900
# LastModified: 2023-02-03 21:27:40 +0900
# Reference: 8ucchiman.jp





.PHONY: clean
clean:
	rm *.png *.pdf *.jpg *.aux *.dvi *.log
