# FileName:     Makefile
# Author: 8ucchiman
# CreatedDate:  2023-02-03 21:27:49 +0900
# LastModified: 2023-02-04 13:25:19 +0900
# Reference: 8ucchiman.jp



.PHONY: run clean

run:
	python main.py datas --target Transported


clean:
	rm *.png *.pdf *.jpg *.aux *.dvi logs/*.log results/*
