# FileName:     {{_file_name_}}
# Author: 		{{_author_}}
# CreatedDate:  {{_date_}}
# LastModified: 2023-02-03 21:27:40 +0900
# Reference: 	8ucchiman.jp


{{_cursor_}}


.PHONY: clean
clean:
	rm *.png *.pdf *.jpg *.aux *.dvi *.log
