# FileName:     <+FILENAME+>
# Author: 8ucchiman
# CreatedDate:  <+DATE+>
# LastModified: 2023-02-03 21:27:40 +0900
# Reference: 8ucchiman.jp

<+CURSOR+>



.PHONY: clean
clean:
	rm *.png *.pdf *.jpg *.aux *.dvi *.log
