#
# FileName:     Makefile
# Author: 		8ucchiman
# CreatedDate:  2023-04-23 14:48:31
# LastModified: 2023-02-03 21:27:40 +0900
# Reference: 	8ucchiman.jp
# Description:	---
#





.PHONY: clean
clean:
	rm *.png *.pdf *.jpg *.aux *.dvi *.log

