# FileName:     Makefile
# Author: 8ucchiman
# CreatedDate:  2023-03-27 11:58:35 +0900
# LastModified: 2023-03-27 12:18:27 +0900
# Reference: 8ucchiman.jp






sample01:
	g++ sample01.cpp -I/usr/include/opencv4/ -lopencv_core -lopencv_videoio -lopencv_highgui -lopencv_imgproc

sample02:


.PHONY: clean
clean:
	rm *.png *.pdf *.jpg *.aux *.dvi *.log a.out
