# FileName:     Makefile
# Author: 8ucchiman
# CreatedDate:  2023-03-27 11:58:35 +0900
# LastModified: 2023-03-27 19:43:23 +0900
# Reference: 8ucchiman.jp






sample01:
	#g++ main.cpp -I/usr/include/opencv4/ -lopencv_core -lopencv_videoio -lopencv_highgui -lopencv_imgproc
	g++ main.cpp -I/usr/include/opencv4/ -lopencv_objdetect -lopencv_features2d -lopencv_imgproc -lopencv_highgui -lopencv_core

sample02:


.PHONY: clean
clean:
	rm *.png *.pdf *.jpg *.aux *.dvi *.log a.out
