# FileName:     Makefile
# Author: 8ucchiman
# CreatedDate:  2023-03-28 10:29:51 +0900
# LastModified: 2023-03-28 10:30:13 +0900
# Reference: 8ucchiman.jp





.PHONY: clean



run:
	g++ -fopenmp -o hello hello_world.cpp


clean:
	rm *.png *.pdf *.jpg *.aux *.dvi *.log
